name: apple_tensorflow
channels:
  - conda-forge
  - nodefaults
dependencies:
  - absl-py
  - astunparse
  - gast
  - google-pasta
  - grpcio
  - h5py
  - ipython
  - keras-preprocessing
  - numpy
  - opt_einsum
  - protobuf
  - python-flatbuffers
  - python=3.8
  - scipy
  - tensorboard
  - tensorflow-estimator
  - termcolor
  - typeguard
  - typing_extensions
  - wheel
  - wrapt
  - pip:
      - adversarial-robustness-toolbox>=1.0.0
      - BlackBoxAuditing
      - tensorflow>=1.13.1,<2
      - cvxpy>=1.0
      - fairlearn==0.4.6
      - tempeh
      - jupyter
      - tqdm
      - pytest>=3.5.0
      - pandas
      - seaborn
      
